services:
  web-app:
    container_name: "todo-backend"
    build: .
    command: "fastapi run src/main.py --reload"
    tty: true
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: "todo-db"
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: